import Navbar from "../components/navbar/Navbar"
import "./home.scss"


const Home = () => {
  return (
    <div className="home">
        <Navbar/>
        <img width="100%" src="https://images.pexels.com/photos/3794359/pexels-photo-3794359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="imgpexel" />
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis repudiandae similique iusto recusandae voluptates porro, cumque doloribus labore, quibusdam eum aliquam quae ea minima perspiciatis magnam aperiam illum dolorem est.
    </div>
  )
}

export default Home